apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: txch0a3ab-python 
  janus-idp.io/tekton: txch0a3ab-python
  backstage.io/kubernetes-id: txch0a3ab-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: txch0a3ab-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml